version: '3.8'
services:
  vnc:
    image: robotont:base
    container_name: robo-2
    hostname: robo-2
    extra_hosts:
      - robotont-11:192.168.0.41
    environment:
      - ROS_MASTER=robotont-11
      - PASSWORD=KYC3f7PKoCczNwAsHHkk
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility
    networks:
      ros_net:
        ipv4_address: 192.168.0.193
networks:
  ros_net:
    external: true
    name: pub_net
