version: '3.8'
services:
  vnc:
    image: robotont:base
    container_name: robo-1
    hostname: robo-1
    extra_hosts:
      - robotont-7:192.168.0.39
    environment:
      - ROS_MASTER=robotont-7
      - PASSWORD=60YRxad4E4XzgWpiD1zr
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - '5901:5901'
      - '6080:6080'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility
networks:
  ros_net:
    external: true
    name: pub_net
