version: '3.8'
services:
  vnc:
    image: robotont:base
    container_name: robo-4
    hostname: robo-4
    extra_hosts:
      - robotont-14:192.168.0.42
    environment:
      - ROS_MASTER=robotont-14
      - PASSWORD=5fs9ABU0hoL6HbRneYTT
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - '5904:5901'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility
networks:
  ros_net:
    external: true
    name: pub_net
